const JS_TOPIC_ORDER = [
  "01-functions",
  "02-scope",
  "03-types-coercion",
  "29-numbers",
  "04-loops",
  "05-strings",
  "05b-unicode",
  "31-regex",
  "06-objects",
  "07-destructuring",
  "09-array-methods",
  "09b-modules",
  "23-immutability",
  "17-map-set",
  "17b-set-operations",
  "17c-grouping",
  "28-json",
  "30-date",
  "08-closures",
  "27-recursion",
  "13-this-bind",
  "14-prototypes",
  "15-classes",
  "16-error-handling",
  "19-debug-logic",
  "10-promises",
  "11-async-await",
  "12-event-loop",
  "16b-async-errors",
  "32-fetch",
  "25-debounce-throttle",
  "25b-debounce-variants",
  "26-debug-async",
  "24-event-emitter",
  "module-01",
  "20-iterators",
  "21-generators",
  "22-property-descriptors",
  "18-weakmap-weakset",
  "module-04",
  "33-debug-perf",
  "34-optimize-data-structures",
  "35-optimize-repeated-work",
  "36-optimize-allocations",
  "37-optimize-async",
  "module-02",
  "module-03",
  "module-05",
  "05c-intl-segmenter",
  "29b-bigint",
  "10b-promise-withresolvers",
  "20b-iterator-helpers",
  "21b-async-generators",
  "22b-proxy-reflect",
  "18b-weakref",
  "27b-trampoline",
  "31b-regex-advanced",
] as const;

const TS_TOPIC_ORDER = [
  "01-basic-types",
  "02-unions-narrowing",
  "02b-advanced-narrowing",
  "03-objects",
  "03b-structural-typing",
  "04-functions",
  "04b-type-operators",
  "05-generics",
  "06-generic-constraints",
  "06b-modern-generics",
  "06c-tuples",
  "07-utility-types",
  "08-mapped-types",
  "09-conditional-types",
  "10-template-literal-types",
  "10b-recursive-types",
  "module-01",
  "11-classes",
  "12-enums-satisfies",
  "13-modules-declarations",
  "13b-module-augmentation",
  "13c-strict-tsconfig",
  "14-debug-types",
  "14b-variance",
  "14c-type-tests",
  "15-optimize-runtime",
  "16-async-types",
  "17-runtime-boundaries",
  "17b-dom-events",
  "18-type-challenges",
  "19-ts-migration",
  "20-modern-features",
  "module-02",
] as const;

const REACT_TOPIC_ORDER = [
  "01-components-props-purity",
  "02-jsx-lists-identity",
  "03-state-snapshot-batching",
  "04-immutable-state",
  "05-accessible-controlled-forms",
  "06-derived-state-no-effect",
  "07-effects-synchronization",
  "08-effect-events",
  "09-fetch-effects",
  "10-refs-ids",
  "11-reducer",
  "12-context",
  "module-01",
  "13-ui-state-modeling",
  "14-form-actions",
  "15-form-status",
  "16-optimistic-updates",
  "17-use-suspense-errors",
  "18-external-store",
  "19-custom-hooks",
  "20-composition-ownership",
  "21-portals-error-boundaries",
  "module-02",
  "22-concurrent-ui",
  "23-refs-layout",
  "24-react-compiler",
  "25-manual-memoization",
  "26-debugging-rendering",
  "26b-optimize-slow-view",
  "27-component-testing",
  "28-accessible-widgets",
  "29-large-lists",
  "30-dynamic-styles",
  "31-server-state",
  "module-03",
] as const;

const NEXT_TOPIC_ORDER = [
  "01-app-router-structure",
  "02-server-client-boundaries",
  "03-server-data-fetching",
  "04-cache-components",
  "05-use-cache",
  "06-revalidation",
  "07-dynamic-routes",
  "08-navigation-url-state",
  "09-loading-errors-not-found",
  "10-server-actions",
  "11-route-handlers",
  "12-metadata-assets",
  "13-auth-data-access",
  "14-proxy",
  "15-streaming",
  "16-accessible-forms",
  "17-testing",
  "18-production-observability",
  "19-debug-next-boundaries",
  "19b-optimize-next",
  "module-01",
  "module-02",
] as const;

const NODE_TOPIC_ORDER = [
  "01-runtime-modules-native-ts",
  "02-process-config",
  "03-url-path-fs",
  "04-buffers-encoding",
  "05-events-cancellation",
  "06-event-loop-async-context",
  "07-http-client",
  "08-http-server",
  "09-streams-backpressure",
  "10-web-streams-compression",
  "11-processes-workers",
  "12-testing",
  "13-crypto-secrets",
  "14-graceful-shutdown",
  "15-observability",
  "16-security-permissions",
  "17-cli",
  "18-debug-optimize-node",
  "19-elective-sqlite",
  "20-elective-websocket",
  "module-01",
  "module-02",
] as const;

const MYSQL_TOPIC_ORDER = [
  "01-query-basics-null",
  "02-types-time-text-json",
  "03-joins",
  "04-aggregates-sql-modes",
  "05-subqueries-ctes-sets",
  "06-window-functions",
  "07-data-modification",
  "08-constraints-relations",
  "09-transactions-savepoints",
  "10-isolation-locking-deadlocks",
  "11-indexes",
  "12-explain-statistics",
  "13-pagination",
  "14-schema-design",
  "15-migrations-backups",
  "16-views-generated-routines",
  "17-users-roles-security",
  "18-observability-performance-schema",
  "19-database-testing",
  "20-mysql2-typescript",
  "21-debugging-sql",
  "21b-optimize-query-plans",
  "module-01",
  "module-02",
] as const;

const STRAPI_TOPIC_ORDER = [
  "01-project-types",
  "02-content-modeling",
  "03-document-service",
  "04-publication-locales",
  "05-rest-querying",
  "06-auth-permissions",
  "07-custom-api-layers",
  "08-policies-http-middleware",
  "09-document-middleware-lifecycles",
  "10-validation-errors-transactions",
  "11-upload-media",
  "12-webhooks-revalidation",
  "13-http-testing",
  "14-debug-strapi",
  "14b-optimize-strapi",
  "module-01",
] as const;

const COMBINED_TOPIC_ORDER = [
  "ts-react-01",
  "ts-react-02",
  "js-node-01",
  "react-next-01",
  "next-strapi-01",
  "next-strapi-02",
  "node-mysql-01",
  "quality-01",
  "security-01",
  "delivery-01",
  "observability-01",
  "full-01",
  "full-02",
] as const;

const JAVA_TOPIC_ORDER = [
  "ppj-01-runtime-numbers", "ppj-02-control-io", "ppj-03-arrays-matrices",
  "ppj-04-text-unicode", "ppj-05-methods-recursion", "ppj-06-sorting-searching",
  "ppj-07-oop-exceptions", "ppj-08-files-debug-performance", "module-ppj",
  "gui-01-abstractions-collections", "gui-02-swing-event-rendering",
  "gui-03-edt-workers", "gui-04-javafx-fxml-css", "gui-05-binding-table-mvc",
  "module-gui-swing", "module-gui-javafx",
  "utp-01-generics-pecs", "utp-02-functional-streams", "utp-03-collectors-collections",
  "utp-04-io-nio-serialization", "utp-05-reflection-beans",
  "utp-06-concurrency-memory", "utp-07-executors-futures",
  "utp-08-i18n-xml-jdbc-patterns", "utp-09-jdk25-modern",
  "module-utp-import", "module-utp-processor",
  "skj-01-network-foundations", "skj-02-application-protocols", "skj-03-tcp-servers",
  "skj-04-udp-framing", "skj-05-http-tls", "skj-06-diagnostics-nio",
  "module-skj-chat", "module-skj-http-client",
  "tpo-01-scalable-nio-rmi", "tpo-02-messaging-web", "tpo-03-jakarta-context",
  "module-tpo",
] as const;

export const TOPIC_ORDER: Readonly<Record<string, readonly string[]>> = {
  js: JS_TOPIC_ORDER,
  ts: TS_TOPIC_ORDER,
  react: REACT_TOPIC_ORDER,
  next: NEXT_TOPIC_ORDER,
  node: NODE_TOPIC_ORDER,
  mysql: MYSQL_TOPIC_ORDER,
  strapi: STRAPI_TOPIC_ORDER,
  combined: COMBINED_TOPIC_ORDER,
  java: JAVA_TOPIC_ORDER,
};

export function compareTopicSlugs(track: string, left: string, right: string): number {
  const order = TOPIC_ORDER[track];
  if (!order) return left.localeCompare(right);

  const leftIndex = order.indexOf(left);
  const rightIndex = order.indexOf(right);
  if (leftIndex === -1 || rightIndex === -1) {
    if (leftIndex === -1 && rightIndex === -1) return left.localeCompare(right);
    return leftIndex === -1 ? 1 : -1;
  }
  return leftIndex - rightIndex;
}

export function topicDisplayNumber(topicId: string): string | null {
  const [track, slug] = topicId.split("/");
  const moduleMatch = slug?.match(/^module-0*(\d+)/);
  if (moduleMatch) return `M${moduleMatch[1]}`;

  const order = TOPIC_ORDER[track];
  const index = order?.indexOf(slug);
  if (index === undefined || index < 0) return null;

  const lessonNumber = order
    .slice(0, index + 1)
    .filter((item) => !item.startsWith("module-"))
    .length;
  return String(lessonNumber).padStart(2, "0");
}
